# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Author.create(first_name: 'Cassandra', last_name: 'Clare')
Author.create(first_name: 'Holly', last_name: 'Black')
Author.create(first_name: 'J.K.', last_name: 'Rowling')
Author.create(first_name: 'Chuck', last_name: 'Yeager')

Book.create(title: 'City of Bones', author_id: 1, genre: 'Fiction', pub_date: '2007-03-27', summary: "hen fifteen-year-old Clary Fray heads out to the Pandemonium Club in New York City, she hardly expects to witness a murder― much less a murder committed by three teenagers covered with strange tattoos and brandishing bizarre weapons. Then the body disappears into thin air. It's hard to call the police when the murderers are invisible to everyone else and when there is nothing―not even a smear of blood―to show that a boy has died. Or was he a boy? This is Clary's first meeting with the Shadowhunters, warriors dedicated to ridding the earth of demons. It's also her first encounter with Jace, a Shadowhunter who looks a little like an angel and acts a lot like a jerk. Within twenty-four hours Clary is pulled into Jace's world with a vengeance when her mother disappears and Clary herself is attacked by a demon. But why would demons be interested in ordinary mundanes like Clary and her mother? And how did Clary suddenly get the Sight? The Shadowhunters would like to know...")

Book.create(title: 'City of Ashes', author_id: 1, genre: 'Fiction', pub_date: '2008-03-25', summary: "Clary Fray just wishes that her life would go back to normal. But what's normal when you're a demon-slaying Shadowhunter, your mother is in a magically induced coma, and you can suddenly see Downworlders like werewolves, vampires, and faeries? If Clary left the world of the Shadowhunters behind, it would mean more time with her best friend, Simon, who's becoming more than a friend. But the Shadowhunting world isn't ready to let her go — especially her handsome, infuriating, newfound brother, Jace. And Clary's only chance to help her mother is to track down rogue Shadowhunter Valentine, who is probably insane, certainly evil — and also her father. To complicate matters, someone in New York City is murdering Downworlder children. Is Valentine behind the killings — and if he is, what is he trying to do? When the second of the Mortal Instruments, the Soul-Sword, is stolen, the terrifying Inquisitor arrives to investigate and zooms right in on Jace. How can Clary stop Valentine if Jace is willing to betray everything he believes in to help their father?")

Book.create(title: 'City of Glass', author_id: 1, genre: 'Fiction', pub_date: '2009-03-24', summary: "could mean death. To make things worse, she learns that Jace does not want her there, and Simon has been thrown in prison by the Shadowhunters, who are deeply suspicious of a vampire who can withstand sunlight. As Clary uncovers more about her family's past, she finds an ally in mysterious Shadowhunter Sebastian. With Valentine mustering the full force of his power to destroy all Shadowhunters forever, their only chance to defeat him is to fight alongside their eternal enemies. But can Downworlders and Shadowhunters put aside their hatred to work together? While Jace realizes exactly how much he's willing to risk for Clary, can she harness her newfound powers to help save the Glass City - whatever the cost?")

Book.create(title: 'Tithe', author_id: 2, genre: 'Fiction', pub_date: '2002-10-01', summary: "Sixteen-year-old Kaye is a modern nomad. Fierce and independent, she travels from city to city with her mother's rock band until an ominous attack forces Kaye back to her childhood home. There, amid the industrial, blue-collar New Jersey backdrop, Kaye soon finds herself an unwilling pawn in an ancient power struggle between two rival faerie kingdoms - a struggle that could very well mean her death. ")

Book.create(title: 'Valiant', author_id: 2, genre: 'Fiction', pub_date: '2005-06-01', summary: "When seventeen-year-old Valerie runs away to New York City, she's trying to escape a life that has utterly betrayed her. Sporting a new identity, she takes up with a gang of squatters who live in the city's labyrinthine subway system. But there's something eerily beguiling about Val's new friends. And when one talks Val into tracking down the lair of a mysterious creature with whom they are all involved, Val finds herself torn between her newfound affection for an honorable monster and her fear of what her new friends are becoming.")

Book.create(title: 'Ironside', author_id: 2, genre: 'Fiction', pub_date: '2008-07-01', summary: "n the realm of Faerie, the time has come for Roiben's coronation. Uneasy in the midst of the malevolent Unseelie Court, pixie Kaye is sure of only one thing -- her love for Roiben. But when Kaye, drunk on faerie wine, declares herself to Roiben, he sends her on a seemingly impossible quest. Now Kaye can't see or speak to Roiben unless she can find the one thing she knows doesn't exist: a faerie who can tell a lie. Miserable and convinced she belongs nowhere, Kaye decides to tell her mother the truth -- that she is a changeling left in place of the human daughter stolen long ago. Her mother's shock and horror sends Kaye back to the world of Faerie to find her human counterpart and return her to Ironside. But once back in the faerie courts, Kaye finds herself a pawn in the games of Silarial, queen of the Seelie Court. Silarial wants Roiben's throne, and she will use Kaye, and any means necessary, to get it. In this game of wits and weapons, can a pixie outplay a queen?")

Book.create(title: "Harry Potter and the Sorcerer's Stone", author_id: 3, genre: 'Fiction', pub_date: '1997-01-28', summary: "Harry Potter's life is miserable. His parents are dead and he's stuck with his heartless relatives, who force him to live in a tiny closet under the stairs. But his fortune changes when he receives a letter that tells him the truth about himself: he's a wizard. A mysterious visitor rescues him from his relatives and takes him to his new home, Hogwarts School of Witchcraft and Wizardry. After a lifetime of bottling up his magical powers, Harry finally feels like a normal kid. But even within the Wizarding community, he is special. He is the boy who lived: the only person to have ever survived a killing curse inflicted by the evil Lord Voldemort, who launched a brutal takeover of the Wizarding world, only to vanish after failing to kill Harry. Though Harry's first year at Hogwarts is the best of his life, not everything is perfect. There is a dangerous secret object hidden within the castle walls, and Harry believes it's his responsibility to prevent it from falling into evil hands. But doing so will bring him into contact with forces more terrifying than he ever could have imagined. Full of sympathetic characters, wildly imaginative situations, and countless exciting details, the first installment in the series assembles an unforgettable magical world and sets the stage for many high-stakes adventures to come.")

Book.create(title: 'Harry Potter and the Chamber of Secrets', author_id: 3, genre: 'Fiction', pub_date: '1999-07-01', summary: "Ever since Harry Potter had come home for the summer, the Dursleys had been so mean and hideous that all Harry wanted was to get back to the Hogwarts School for Witchcraft and Wizardry. But just as he’s packing his bags, Harry receives a warning from a strange impish creature who says that if Harry returns to Hogwarts, disaster will strike. And strike it does. For in Harry’s second year at Hogwarts, fresh torments and horrors arise, including an outrageously stuck-up new professor and a spirit who haunts the girls’ bathroom. But then the real trouble begins – someone is turning Hogwarts students to stone. Could it be Draco Malfoy, a more poisonous rival than ever? Could it possible be Hagrid, whose mysterious past is finally told? Or could it be the one everyone at Hogwarts most suspects… Harry Potter himself!")

Book.create(title: 'Harry Potter and the Prisoner of Azkaban ', author_id: 3, genre: 'Fiction', pub_date: '2001-09-11', summary: "For twelve long years, the dread fortress of Azkaban held an infamous prisoner named Sirius Black. Convicted of killing thirteen people with a single curse, he was said to be the heir apparent to the Dark Lord, Voldemort. Now he has escaped, leaving only two clues as to where he might be headed: Harry Potter's defeat of You-Know-Who was Black's downfall as well. And the Azkaban guards heard Black muttering in his sleep, 'He's at Hogwarts . . . he's at Hogwarts.' Harry Potter isn't safe, not even within the walls of his magical school, surrounded by his friends. Because on top of it all, there may well be a traitor in their midst.")

Book.create(title: 'Harry Potter and the Goblet of Fire', author_id: 3, genre: 'Fiction', pub_date: '2002-09-28', summary: "Harry Potter is midway through his training as a wizard and his coming of age. Harry wants to get away from the pernicious Dursleys and go to the International Quidditch Cup with Hermione, Ron, and the Weasleys. He wants to dream about Cho Chang, his crush (and maybe do more than dream). He wants to find out about the mysterious event that's supposed to take place at Hogwarts this year, an event involving two other rival schools of magic, and a competition that hasn't happened for hundreds of years. He wants to be a normal, fourteen-year-old wizard. But unfortunately for Harry Potter, he's not normal - even by wizarding standards. And in his case, different can be deadly.")

Book.create(title: 'Harry Potter and the Order of the Phoenix', author_id: 3, genre: 'Fiction', pub_date: '2004-08-10', summary: "There is a door at the end of a silent corridor. And it’s haunting Harry Pottter’s dreams. Why else would he be waking in the middle of the night, screaming in terror? Harry has a lot on his mind for this, his fifth year at Hogwarts: a Defense Against the Dark Arts teacher with a personality like poisoned honey; a big surprise on the Gryffindor Quidditch team; and the looming terror of the Ordinary Wizarding Level exams. But all these things pale next to the growing threat of He-Who-Must-Not-Be-Named - a threat that neither the magical government nor the authorities at Hogwarts can stop. As the grasp of darkness tightens, Harry must discover the true depth and strength of his friends, the importance of boundless loyalty, and the shocking price of unbearable sacrifice. His fate depends on them all.")

Book.create(title: 'Harry Potter and the Half-Blood Prince', author_id: 3, genre: 'Fiction', pub_date: '2006-07-25', summary: "The war against Voldemort is not going well; even Muggle governments are noticing. Ron scans the obituary pages of the Daily Prophet, looking for familiar names. Dumbledore is absent from Hogwarts for long stretches of time, and the Order of the Phoenix has already suffered losses. And yet . . . As in all wars, life goes on. The Weasley twins expand their business. Sixth-year students learn to Apparate - and lose a few eyebrows in the process. Teenagers flirt and fight and fall in love. Classes are never straightforward, through Harry receives some extraordinary help from the mysterious Half-Blood Prince. So it's the home front that takes center stage in the multilayered sixth installment of the story of Harry Potter. Here at Hogwarts, Harry will search for the full and complete story of the boy who became Lord Voldemort - and thereby find what may be his only vulnerability.")

Book.create(title: 'Harry Potter and the Deathly Hallows', author_id: 3, genre: 'Fiction', pub_date: '2009-07-07', summary: "Harry Potter is leaving Privet Drive for the last time. But as he climbs into the sidecar of Hagrid’s motorbike and they take to the skies, he knows Lord Voldemort and the Death Eaters will not be far behind. The protective charm that has kept him safe until now is broken. But the Dark Lord is breathing fear into everything he loves. And he knows he can’t keep hiding. To stop Voldemort, Harry knows he must find the remaining Horcruxes and destroy them. He will have to face his enemy in one final battle.")

Book.create(title: 'Yeager: An Autobiography', author_id: 4, genre: 'Non-Fiction', pub_date: '1986-08-01', summary: "General Chuck Yeager, the greatest test pilot of them all -- the first man to fly faster than the speed of sound . . .the World War II flying ace who shot down a Messerschmitt jet with a prop-driven P-51 Mustang . . .the hero who defined a certain quality that all hotshot fly-boys of the postwar era aimed to achieve: the right stuff.")